In [2]:
print("Hola Científicos")


Hola Científicos


In [3]:
import numpy as np

In [4]:
lista = [
    [1, 2, 3, 4],
    [3, 4, 5, 6],
    [5, 6, 7, 8]
]

array_1d = np.array(lista, dtype='float')

In [5]:
# Checamos el tipo de dato del array
type(array_1d)

numpy.ndarray

In [6]:
print("Dimensiones:", array_1d.ndim)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Tipo de dato:", array_1d.dtype)

Dimensiones: 2
Shape: (3, 4)
Size: 12
Tipo de dato: float64


In [7]:
def generar_matriz_numpy(N):
    matriz = np.random.randint(1, 10, size=(N, N))
    return matriz

In [8]:
N = 5

matriz_aleatoria = generar_matriz_numpy(N)

print(matriz_aleatoria)

[[6 1 4 1 1]
 [5 7 6 9 2]
 [4 8 4 1 6]
 [7 3 9 2 8]
 [3 5 2 6 9]]


In [9]:
def imprimir_matriz(matriz):
    for fila in matriz:
        fila_formateada = ' '.join(f'{elemento:2}' for elemento in fila)
        print(fila_formateada)

In [10]:
print("Matriz de 5x5 con NumPy")
m_5 = generar_matriz_numpy(5)
imprimir_matriz(m_5)

print("============")

print("Matriz de 10x10 con NumPy")
m_10 = generar_matriz_numpy(10)
imprimir_matriz(m_10)

print("============")

print("Matriz de 20x20 con NumPy")
m_20 = generar_matriz_numpy(20)
imprimir_matriz(m_20)

Matriz de 5x5 con NumPy
 7  3  5  7  9
 2  2  2  1  8
 4  2  3  4  1
 2  5  7  4  8
 1  6  1  2  8
Matriz de 10x10 con NumPy
 9  3  4  6  4  6  1  4  2  3
 4  7  1  1  1  9  4  2  1  5
 2  2  5  3  9  6  6  7  6  9
 2  4  2  8  6  1  1  9  1  8
 3  3  2  7  7  6  3  8  8  7
 6  1  4  6  4  3  7  7  1  5
 8  3  3  9  4  3  8  4  4  9
 5  3  7  9  1  9  2  6  2  5
 8  7  2  2  6  8  9  9  1  1
 2  7  7  6  4  8  3  4  8  7
Matriz de 20x20 con NumPy
 1  2  8  6  9  5  5  7  4  4  6  2  2  3  1  2  2  6  1  5
 2  1  6  1  7  8  3  8  6  7  8  9  1  5  1  9  6  7  3  7
 7  2  9  7  5  5  3  3  3  5  6  4  3  6  1  2  1  5  6  4
 5  3  3  8  1  9  6  2  6  9  1  9  6  8  2  7  6  5  9  5
 5  3  9  4  9  7  3  6  3  5  1  9  1  2  6  6  5  5  9  4
 7  7  5  8  4  9  9  3  8  2  5  6  5  9  3  9  1  1  5  2
 5  7  9  4  8  9  3  7  4  6  4  3  8  6  5  8  6  4  4  8
 6  6  4  6  3  8  4  6  7  3  8  7  6  9  1  7  3  5  8  6
 2  2  3  5  8  1  6  6  4  5  3  2  3  1  2  1  3  5  5  4
 3  2  7 

In [11]:
print("Propiedades de m_5")
print("Dimensiones:", m_5.ndim)
print("Shape:", m_5.shape)
print("Size:", m_5.size)
print("Tipo de dato:", m_5.dtype)

print("============")

print("Propiedades de m_10")
print("Dimensiones:", m_10.ndim)
print("Shape:", m_10.shape)
print("Size:", m_10.size)
print("Tipo de dato:", m_10.dtype)

print("============")

print("Propiedades de m_20")
print("Dimensiones:", m_20.ndim)
print("Shape:", m_20.shape)
print("Size:", m_20.size)
print("Tipo de dato:", m_20.dtype)

Propiedades de m_5
Dimensiones: 2
Shape: (5, 5)
Size: 25
Tipo de dato: int64
Propiedades de m_10
Dimensiones: 2
Shape: (10, 10)
Size: 100
Tipo de dato: int64
Propiedades de m_20
Dimensiones: 2
Shape: (20, 20)
Size: 400
Tipo de dato: int64


In [12]:
print("Suma de todos los elementos de m_5:", np.sum(m_5))
print("Promedio de m_5:", np.mean(m_5))
print("Valor máximo de m_5:", np.max(m_5))
print("Valor mínimo de m_5:", np.min(m_5))

Suma de todos los elementos de m_5: 104
Promedio de m_5: 4.16
Valor máximo de m_5: 9
Valor mínimo de m_5: 1


In [13]:
print("Primera fila de m_5:")
print(m_5[0])

print("Primera columna de m_5:")
print(m_5[:, 0])

print("Elemento en fila 2, columna 3:")
print(m_5[1, 2])

Primera fila de m_5:
[7 3 5 7 9]
Primera columna de m_5:
[7 2 4 2 1]
Elemento en fila 2, columna 3:
2
